name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{a14e2130-114c-49b0-9563-0d42e058c86a}}
          heroku_app_name: "tourtravelapp-swetha" #Must be unique in Heroku
          heroku_email: "sswethasri6@gmail.com"
